#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'0.8.7',
 'build_date': '2011-10-12 15:54:34 +0200',
 'clean': None,
 'date': '2011-10-11 18:30:38 +0200',
 'revision_id': 'nico@inattendu.org-20111011163038-be6sjaj6k41ck832',
 'revno': 84}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
